import {Ciudad} from "../model/ciudad";

export class CiudadesList {
  ciudades: Ciudad[] = [
    {id: 1, pais: 5, nombre: "Bogotá"},
    {id: 2, pais: 5, nombre: "Medellín"},
    {id: 3, pais: 5, nombre: "Cali"},
    {id: 4, pais: 5, nombre: "Barranquilla"},
    {id: 5, pais: 5, nombre: "Cartagena"},
    {id: 6, pais: 5, nombre: "Cúcuta"},
    {id: 7, pais: 5, nombre: "Soacha"},
    {id: 8, pais: 5, nombre: "Soledad"},
    {id: 9, pais: 5, nombre: "Bucaramanga"},
    {id: 10, pais: 5, nombre: "Bello"},
    {id: 11, pais: 5, nombre: "Villavicencio"},
    {id: 12, pais: 5, nombre: "Ibagué"},
    {id: 13, pais: 5, nombre: "Santa Marta"},
    {id: 14, pais: 5, nombre: "Valledupar"},
    {id: 15, pais: 5, nombre: "Montería"},
    {id: 16, pais: 5, nombre: "Pereira"},
    {id: 17, pais: 5, nombre: "Manizales"},
    {id: 18, pais: 5, nombre: "Pasto"},
    {id: 19, pais: 5, nombre: "Neiva"},
    {id: 20, pais: 5, nombre: "Palmira"},
    {id: 21, pais: 5, nombre: "Popayán"},
    {id: 22, pais: 5, nombre: "Buenaventura"},
    {id: 23, pais: 5, nombre: "Floridablanca"},
    {id: 24, pais: 5, nombre: "Armenia"},
    {id: 25, pais: 5, nombre: "Sincelejo"},
    {id: 26, pais: 5, nombre: "Itagüí"},
    {id: 27, pais: 5, nombre: "Tumaco"},
    {id: 28, pais: 5, nombre: "Envigado"},
    {id: 29, pais: 5, nombre: "Dosquebradas"},
    {id: 30, pais: 5, nombre: "Tuluá"},
    {id: 31, pais: 5, nombre: "Barrancabermeja"},
    {id: 32, pais: 5, nombre: "Riohacha"},
    {id: 33, pais: 1, nombre: "Buenos Aires"},
    {id: 34, pais: 1, nombre: "Córdoba"},
    {id: 35, pais: 1, nombre: "Rosario"},
    {id: 36, pais: 1, nombre: "Mar del Plata"},
    {id: 37, pais: 1, nombre: "San Miguel de Tucumán"},
    {id: 38, pais: 1, nombre: "Salta"},
    {id: 39, pais: 1, nombre: "Santa Fe"},
    {id: 40, pais: 1, nombre: "Corrientes"},
    {id: 41, pais: 1, nombre: "Bahía Blanca"},
    {id: 42, pais: 1, nombre: "Resistencia"},
    {id: 43, pais: 1, nombre: "Posadas"},
    {id: 44, pais: 1, nombre: "Merlo"},
    {id: 45, pais: 1, nombre: "Quilmes"},
    {id: 46, pais: 1, nombre: "San Salvador de Jujuy"},
    {id: 47, pais: 1, nombre: "Guaymallén"},
    {id: 48, pais: 1, nombre: "Santiago del Estero"},
    {id: 49, pais: 1, nombre: "Gregorio de Laferrere"},
    {id: 50, pais: 1, nombre: "José C. Paz"},
    {id: 51, pais: 1, nombre: "Paraná"},
    {id: 52, pais: 1, nombre: "Banfield"},
    {id: 53, pais: 1, nombre: "González Catán"},
    {id: 54, pais: 1, nombre: "Neuquén"},
    {id: 55, pais: 1, nombre: "Formosa"},
    {id: 56, pais: 1, nombre: "Lanús"},
    {id: 57, pais: 1, nombre: "La Plata"},
    {id: 58, pais: 1, nombre: "Godoy Cruz"},
    {id: 59, pais: 1, nombre: "Isidro Casanova"},
    {id: 60, pais: 1, nombre: "Las Heras"},
    {id: 61, pais: 1, nombre: "Berazategui"},
    {id: 62, pais: 1, nombre: "La Rioja"},
    {id: 63, pais: 1, nombre: "Comodoro Rivadavia"},
    {id: 64, pais: 1, nombre: "Moreno"},
    {id: 65, pais: 1, nombre: "San Luis"},
    {id: 66, pais: 1, nombre: "San Miguel"},
    {id: 67, pais: 1, nombre: "San Fernando del Valle de Catamarca"},
    {id: 68, pais: 1, nombre: "Río Cuarto"},
    {id: 69, pais: 1, nombre: "Virrey del Pino"},
    {id: 70, pais: 2, nombre: "Chuquisaca"},
    {id: 71, pais: 2, nombre: "La Paz"},
    {id: 72, pais: 2, nombre: "Cochabamba"},
    {id: 73, pais: 2, nombre: "Oruro"},
    {id: 74, pais: 2, nombre: "Potosí"},
    {id: 75, pais: 2, nombre: "Tarija"},
    {id: 76, pais: 2, nombre: "Santa Cruz"},
    {id: 77, pais: 2, nombre: "Beni"},
    {id: 78, pais: 2, nombre: "Pando"},
    {id: 79, pais: 3, nombre: "São Paulo"},
    {id: 80, pais: 3, nombre: "Río de Janeiro"},
    {id: 81, pais: 3, nombre: "Brasilia"},
    {id: 82, pais: 3, nombre: "Salvador de Bahía"},
    {id: 83, pais: 3, nombre: "Fortaleza"},
    {id: 84, pais: 3, nombre: "Belo Horizonte"},
    {id: 85, pais: 3, nombre: "Manaus"},
    {id: 86, pais: 3, nombre: "Curitiba"},
    {id: 87, pais: 3, nombre: "Recife"},
    {id: 88, pais: 3, nombre: "Porto Alegre"},
    {id: 89, pais: 3, nombre: "Goiânia"},
    {id: 90, pais: 3, nombre: "Belém"},
    {id: 91, pais: 3, nombre: "Guarulhos"},
    {id: 92, pais: 3, nombre: "Campinas"},
    {id: 93, pais: 3, nombre: "São Luís"},
    {id: 94, pais: 3, nombre: "São Gonçalo"},
    {id: 95, pais: 3, nombre: "Maceió"},
    {id: 96, pais: 3, nombre: "Duque de Caxias"},
    {id: 97, pais: 3, nombre: "Natal"},
    {id: 98, pais: 3, nombre: "Campo Grande"},
    {id: 99, pais: 3, nombre: "Teresina"},
    {id: 100, pais: 3, nombre: "São Bernardo do Campo"},
    {id: 101, pais: 3, nombre: "João Pessoa"},
    {id: 102, pais: 3, nombre: "Nova Iguaçu"},
    {id: 103, pais: 3, nombre: "Santo André"},
    {id: 104, pais: 3, nombre: "São José dos Campos"},
    {id: 105, pais: 3, nombre: "Osasco"},
    {id: 106, pais: 3, nombre: "Jaboatão dos Guararapes"},
    {id: 107, pais: 3, nombre: "Ribeirão Preto"},
    {id: 108, pais: 3, nombre: "Uberlândia"},
    {id: 109, pais: 3, nombre: "Sorocaba"},
    {id: 110, pais: 3, nombre: "Contagem"},
    {id: 111, pais: 3, nombre: "Aracaju"},
    {id: 112, pais: 3, nombre: "Feira de Santana"},
    {id: 113, pais: 3, nombre: "Cuiabá"},
    {id: 114, pais: 3, nombre: "Joinville"},
    {id: 115, pais: 3, nombre: "Juiz de Fora"},
    {id: 116, pais: 4, nombre: "Gran Santiago"},
    {id: 117, pais: 4, nombre: "Gran Valparaíso"},
    {id: 118, pais: 4, nombre: "Gran Concepción"},
    {id: 119, pais: 4, nombre: "Gran La Serena"},
    {id: 120, pais: 4, nombre: "Antofagasta"},
    {id: 121, pais: 4, nombre: "Gran Iquique"},
    {id: 122, pais: 4, nombre: "Gran Rancagua"},
    {id: 123, pais: 4, nombre: "Gran Temuc"},
    {id: 124, pais: 4, nombre: "Gran Talc"},
    {id: 125, pais: 4, nombre: "Aric"},
    {id: 126, pais: 4, nombre: "Puerto Mon"},
    {id: 127, pais: 4, nombre: "Gran Chillán"},
    {id: 128, pais: 4, nombre: "Calama"},
    {id: 129, pais: 4, nombre: "Copiapó "},
    {id: 130, pais: 4, nombre: "Valdivi"},
    {id: 131, pais: 4, nombre: "Gran Quill"},
    {id: 132, pais: 4, nombre: "Osorno"},
    {id: 133, pais: 4, nombre: "Los Ángele"},
    {id: 134, pais: 4, nombre: "Curicó"},
    {id: 135, pais: 4, nombre: "Punta Arenas"},
    {id: 136, pais: 4, nombre: "Gran San Antonio"},
    {id: 137, pais: 4, nombre: "Coronel"},
    {id: 138, pais: 4, nombre: "Colina"},
    {id: 139, pais: 4, nombre: "Peñaflor"},
    {id: 140, pais: 4, nombre: "Ovall"},
    {id: 141, pais: 4, nombre: "Linares"},
    {id: 142, pais: 4, nombre: "Melipil"},
    {id: 143, pais: 4, nombre: "Buin"},
  ]
}
